version: 2

models:
  - name: dim_customer
    description: "Dimensión de clientes de ClassicModels"
    columns:
      - name: customer_number
        tests:
          - not_null
          - unique
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_unique

      - name: credit_limit
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

  - name: fact_sales
    description: "Tabla de hechos de ventas a nivel orden-producto"
    columns:
      - name: order_number
        tests:
          - not_null

      - name: customer_number
        tests:
          - not_null

      - name: product_code
        tests:
          - not_null

      - name: quantity_ordered
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1

      - name: price_each
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

      - name: sales_amount
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1